version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    image: richnet/nginx:1.19.6
    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - $PWD/conf.d:/etc/nginx/conf.d             #config file folder
      - $PWD/nginx.conf:/etc/nginx/nginx.conf     #nginx main config flie
      - $PWD/quic.conf:/etc/nginx/quic.conf       #quic include file
      - $PWD/BLOCK.conf:/etc/nginx/BLOCK.conf     #block bots include file
      - $PWD/TLS1_3.conf:/etc/nginx/TLS1_3.conf   #tls and ssl config file
      - $PWD/log:/var/log/nginx                   #logs folder
      - $PWD/www:/var/www                         #web file folder
      - $PWD/ssl:/etc/nginx/ssl                   #ssl keys folder
    environment:
      - TZ=Asia/Taipei